// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

console.log($$Array.fold_left((function (prim, prim$1) {
            return prim + prim$1 | 0;
          }), 0, $$Array.map(Caml_format.caml_int_of_string, Fs.readFileSync("./src/day-1-input.txt", "utf8").split("\n"))));

/*  Not a pure module */
