// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Belt_SetInt = require("bs-platform/lib/js/belt_SetInt.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var data = $$Array.to_list($$Array.map(Caml_format.caml_int_of_string, Fs.readFileSync("./src/day-1-input.txt", "utf8").split("\n")));

function findDuplicateFreq(_seenFreqs, _currentFreq, _freqs) {
  while(true) {
    var freqs = _freqs;
    var currentFreq = _currentFreq;
    var seenFreqs = _seenFreqs;
    if (freqs) {
      var nextFreq = currentFreq + freqs[0] | 0;
      if (Belt_SetInt.has(seenFreqs, nextFreq) === true) {
        return nextFreq;
      } else {
        _freqs = freqs[1];
        _currentFreq = nextFreq;
        _seenFreqs = Belt_SetInt.add(seenFreqs, nextFreq);
        continue ;
      }
    } else {
      _freqs = data;
      continue ;
    }
  };
}

console.log(findDuplicateFreq(Belt_SetInt.fromArray(/* array */[0]), 0, data));

exports.data = data;
exports.findDuplicateFreq = findDuplicateFreq;
/* data Not a pure module */
