// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function letterFrequencies(str) {
  return str.split("").reduce((function (acc, value) {
                var match = Js_dict.get(acc, value);
                var count = match !== undefined ? match + 1 | 0 : 1;
                acc[value] = count;
                return acc;
              }), { });
}

function hasTwoOrThree(x) {
  return Js_dict.values(x).reduce((function (acc, value) {
                if (value !== 2) {
                  if (value !== 3) {
                    return acc;
                  } else {
                    return /* tuple */[
                            acc[0],
                            true
                          ];
                  }
                } else {
                  return /* tuple */[
                          true,
                          acc[1]
                        ];
                }
              }), /* tuple */[
              false,
              false
            ]);
}

function calculateChecksum(x) {
  var match = x.reduce((function (acc, value) {
          var numThrees = acc[1];
          var numTwos = acc[0];
          if (value[0]) {
            if (value[1]) {
              return /* tuple */[
                      numTwos + 1 | 0,
                      numThrees + 1 | 0
                    ];
            } else {
              return /* tuple */[
                      numTwos + 1 | 0,
                      numThrees
                    ];
            }
          } else if (value[1]) {
            return /* tuple */[
                    numTwos,
                    numThrees + 1 | 0
                  ];
          } else {
            return acc;
          }
        }), /* tuple */[
        0,
        0
      ]);
  return Caml_int32.imul(match[0], match[1]);
}

var result = calculateChecksum(Fs.readFileSync("./src/day-2-input.txt", "utf8").split("\n").map(letterFrequencies).map(hasTwoOrThree));

console.log(result);

exports.letterFrequencies = letterFrequencies;
exports.hasTwoOrThree = hasTwoOrThree;
exports.calculateChecksum = calculateChecksum;
exports.result = result;
/* result Not a pure module */
